services:
  tnm-customer-ussd-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3005

  airtel-customer-ussd-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3006
