version: '3.8'

services:
  tnm-customer-ussd-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${TNM_PORT}:${TNM_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  airtel-customer-ussd-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${AIRTEL_PORT}:${AIRTEL_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
